version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  
